#!/usr/bin/env node
/**
 * Assemble the combined Pages deploy that ENABLES the UI redesign behind the
 * strangler edge map, for a PREVIEW deploy (production DNS untouched).
 *
 * Output `dist/`:
 *   • legacy stamped dashboard at the root      (via stamp-assets → dist/)
 *   • the new TanStack app's bundle             (cloud/web/dist/assets → dist/assets,
 *                                                its index.html → dist/_web.html)
 *   • _worker.js (advanced mode)                (serves _web for owned nav paths)
 *
 * The worker embeds the SAME OWNED_PATHS + resolveSurface as cloud/web
 * (parsed from the source so the map never forks) and the pure serveDecision
 * from webEnable.mjs. Preview: `wrangler pages deploy dist --branch <preview>`.
 *
 * Usage: node scripts/web-enable.mjs
 *   Assumes `npm run build:dashboard` (→ dist/) and the cloud/web build
 *   (→ cloud/web/dist) have already run; this script wires them together.
 */
import { readFileSync, writeFileSync, cpSync, existsSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { extractOwnedArray, NEW_APP_ENTRY } from "./webEnable.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const cloudRoot = resolve(here, "..");
const dist = resolve(cloudRoot, "dist"); // legacy stamped dashboard already here
const webDist = resolve(cloudRoot, "web", "dist"); // the new app's vite build

function fail(msg) {
  console.error(`web-enable: ${msg}`);
  process.exit(1);
}

if (!existsSync(join(dist, "index.html"))) {
  fail("dist/index.html missing — run `npm run build:dashboard` first (legacy root).");
}
if (!existsSync(join(webDist, "index.html"))) {
  fail("cloud/web/dist/index.html missing — run the cloud/web build first.");
}

// 1. New app assets → dist/assets (no legacy collision: legacy uses app.js/styles.css)
cpSync(join(webDist, "assets"), join(dist, "assets"), { recursive: true });

// 2. New app HTML entry → dist/_web.html (NOT index.html; that stays legacy)
writeFileSync(join(dist, "_web.html"), readFileSync(join(webDist, "index.html")));

// 3. Extract OWNED_PATHS from the single source (cloud/web/src/shell/edgeRoutes.ts)
//    so the middleware map can never drift from the app's.
const edgeSrc = readFileSync(
  resolve(cloudRoot, "web", "src", "shell", "edgeRoutes.ts"),
  "utf8",
);
const ownedLiteral = extractOwnedArray(edgeSrc);
if (!ownedLiteral) fail("could not parse OWNED_PATHS from edgeRoutes.ts");

// 4. Emit the Pages middleware (plain JS; no bundler). Embeds resolveSurface +
//    the parsed OWNED_PATHS + the pure serveDecision logic inline.
// Advanced mode: a single `_worker.js` at the deploy ROOT that Pages ALWAYS
// runs (the functions/ directory convention silently failed — the dir landed
// inside the assets output and was never registered as a Function). The worker
// fetches static assets via env.ASSETS and rewrites owned navigation paths to
// the new app's shell.
const worker = `// @generated by scripts/web-enable.mjs — do not edit.
// Strangler edge: serve the new TanStack app (${NEW_APP_ENTRY}) for owned
// navigation paths, pass everything else (legacy pages, /assets/*, files)
// through to the static asset store.
const OWNED_PATHS = ${ownedLiteral};

function resolveSurface(pathname) {
  const p = pathname.replace(/\\/+$/, "") || "/";
  const owned = OWNED_PATHS.some((o) => {
    if (o instanceof RegExp) return o.test(p);
    const b = o.replace(/\\/+$/, "") || "/";
    return p === b || p.startsWith(b + "/");
  });
  return owned ? "web" : "legacy";
}

function isNavigationRequest(method, pathname, accept) {
  if (method !== "GET" && method !== "HEAD") return false;
  if (pathname.startsWith("/assets/")) return false;
  const last = pathname.split("/").pop() || "";
  if (last.includes(".")) return false;
  if (accept && !accept.includes("text/html") && !accept.includes("*/*")) return false;
  return true;
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const accept = request.headers.get("accept") || "";
    if (isNavigationRequest(request.method, url.pathname, accept) && resolveSurface(url.pathname) === "web") {
      // Serve the new app's shell; the SPA router takes the path from there.
      // ${NEW_APP_ENTRY} is extensionless — Pages 308-redirects *.html away.
      return env.ASSETS.fetch(new Request(new URL("${NEW_APP_ENTRY}", url), request));
    }
    return env.ASSETS.fetch(request);
  },
};
`;
writeFileSync(join(dist, "_worker.js"), worker);

console.log("web-enable: combined dist ready.");
console.log("  legacy root + new app at ${NEW_APP_ENTRY} + _worker.js (advanced mode)");
console.log("  preview (isolated project — never touches production):");
console.log("    npm run deploy:web-preview");
console.log("    → wrangler pages deploy dist --project-name store-ops-web-preview");
